services:
  app:
    build:
      path: .
      manifest: compose/prod/php-fpm/Dockerfile
    port: 80
    health: /ping
    command: /app.sh
    environment:
      - "*"

  scheduler:
    build:
      path: .
      manifest: compose/prod/php-fpm/Dockerfile
    command: /scheduler.sh
    environment:
      - "*"

  worker:
    build:
      path: .
      manifest: compose/prod/php-fpm/Dockerfile
    command: /worker.sh
    environment:
      - "*"
